### ISSUE TITLE
QR code not created

### ISSUE THREAD

**Issue by myorbit** [ticktronaut/schablone#2]
QR code ist not created for the SMD example. Therefore it can not find the png image which then throws an error. The reason is that it relies on the command `dmtxwrite` which needs libdmtx. But it should use pyqrcode instead.

```
sh: dmtxwrite: command not found
sed: couldn't flush stdout: Broken pipe
Traceback (most recent call last):
  File "./sample.py", line 42, in <module>
    smdLabel.save(fn)
  File "/usr/lib/python3.5/site-packages/schablone/label.py", line 129, in save
    super(smd_container, self).save_substitutes()
  File "/usr/lib/python3.5/site-packages/schablone/generic.py", line 143, in save_substitutes
    tpl.set_image(cpt_key, file=cpt_val, mimetype='image/png')
  File "/usr/lib/python3.5/site-packages/svglue/__init__.py", line 98, in set_image
    file = open(file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'samples/smd_container/smd_caption_120k_qr.png'
```

**Comment by myorbit** [comment]
With the latest version of schablone-0.2.dev3 I don't get an error anymore when generating a SMD container. The data matrix code will be generated as a png image and all the text is correct.
